/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Component;
import java.awt.FlowLayout;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class CreateInformation extends javax.swing.JPanel {

    /**
     * Creates new form CreateInformation
     */
    public CreateInformation(String[] columnIdentifiers) {
        initComponents();
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        System.out.println("agregando...");
        for (String columnIdentifier : columnIdentifiers) {
            System.out.println(columnIdentifier);
            if (columnIdentifier.contains("|t")) {
                JLabel jl = new JLabel();
                jl.setText("%s :".formatted(columnIdentifier.split("\\|")[0]));
                jl.setAlignmentX(Component.LEFT_ALIGNMENT);
                JTextField infoToAdd = new JTextField(10);
                this.add(jl);
                this.add(infoToAdd);
            }
        }
        JPanel panelBotones = new JPanel();
        panelBotones.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10)); // Centrados y con separación

        // 5. Crear y agregar los botones al panel secundario
        JButton btnGuardar = new JButton("Guardar");
        JButton btnCancelar = new JButton("Cancelar");
        panelBotones.add(btnGuardar);
        panelBotones.add(btnCancelar);
        panelBotones.setAlignmentX(Component.LEFT_ALIGNMENT);

        this.add(panelBotones);
        this.revalidate();
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
