package views;

import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Usuario
 */
public class InformationOfOption extends javax.swing.JPanel {

    /**
     * Creates new form ProductosTable
     */
    DefaultTableModel table;

    public InformationOfOption(String[] columnIdentifiers, String key) {
        initComponents();
        configuringBotons( key);
        table = new DefaultTableModel();
        table.setColumnIdentifiers(columnIdentifiers);
        Object[] row = new Object[columnIdentifiers.length-1];
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < columnIdentifiers.length-1; j++) {
                System.out.println((i + 1) * (j + 1));
                row[j] = (i + 1) * (j + 1);
            }
            table.addRow(row);
        }
        informationTbl.setModel(table);
        

    }

    private void configuringBotons(String key) {
        searcher.setText("Buscar %s".formatted(key));
        newSomething.setText("Agregar %s".formatted(key));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searcher = new javax.swing.JTextField();
        newSomething = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        informationTbl = new javax.swing.JTable();

        searcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcherActionPerformed(evt);
            }
        });

        informationTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(informationTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(searcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(newSomething)
                .addGap(42, 42, 42))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSomething, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searcherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable informationTbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newSomething;
    private javax.swing.JTextField searcher;
    // End of variables declaration//GEN-END:variables
}
