package views;

import com.google.gson.JsonArray;
import com.google.gson.JsonParser;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import okhttp3.Request;
import okhttp3.Response;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Usuario
 */
public class InformationOfOption extends javax.swing.JPanel {

    /**
     * Creates new form ProductosTable
     */
    String[] columnIdentifiers;
    String key;
    DefaultTableModel table;
    CreateInformation ci;
    JTableHeader headers;

    public InformationOfOption(String[] columnIdentifiers, String key) {
        this.columnIdentifiers = columnIdentifiers;
        this.key = key;
        initComponents();
        configuringBotons(key.replaceAll(".$", ""));

        table = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        RequestForGetProducts(key, columnIdentifiers,"1");
        informationTbl.setModel(table);
        headers = informationTbl.getTableHeader();

    }

    private void RequestForGetProducts(String key1, String[] columnIdentifiers1,String sort) throws Error {
        Request req = Connection.createBuilder("/%s/%s".formatted(key1.toLowerCase(),sort)).get().build();
        try (Response res = Connection.getClient().newCall(req).execute()) {
            if (res.isSuccessful()) {
                JsonArray body = JsonParser.parseString(res.body().string()).getAsJsonArray();
                String[] forTitles = Arrays.stream(columnIdentifiers1).map(x -> x.split("\\|")[0]).toArray(String[]::new);
                table.setColumnIdentifiers(forTitles);
                Object[] row = new Object[columnIdentifiers1.length - 1];
                for (int i = 0; i < body.size(); i++) {
                    for (int j = 0; j < columnIdentifiers1.length - 1; j++) {
                        row[j] = body.get(i).getAsJsonObject().get(columnIdentifiers1[j].split("\\|")[0]).getAsString();
                    }
                    table.addRow(row);
                }
                informationTbl.setModel(table);
                
            }
        }catch (Exception e) {
            throw new Error(e);
        }
    }

    private void configuringBotons(String key) {
        searcher.setText("Buscar %s".formatted(key));
        newSomething.setText("Agregar %s".formatted(key));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searcher = new javax.swing.JTextField();
        newSomething = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        informationTbl = new javax.swing.JTable();
        informationTbl.getTableHeader().addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                int colVisual = informationTbl.getTableHeader().columnAtPoint(e.getPoint());
                if (colVisual != -1) {
                    String nombre = informationTbl.getColumnName(colVisual);            
                    table.setRowCount(0);
                    System.out.println("me tocaron");
                    System.out.println(nombre);
                    RequestForGetProducts(key, columnIdentifiers, nombre);
                }
            }
        });

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                addSome(evt);
            }
        });

        searcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcherActionPerformed(evt);
            }
        });

        newSomething.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSomethingActionPerformed(evt);
            }
        });

        informationTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        informationTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informationTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(informationTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(searcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(newSomething)
                .addGap(42, 42, 42))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSomething, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searcherActionPerformed

    private void addSome(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_addSome
        addSome();
    }//GEN-LAST:event_addSome

    private void newSomethingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSomethingActionPerformed
        addSome();
        ci = new CreateInformation(columnIdentifiers);
        JFrame jf = (JFrame) SwingUtilities.getWindowAncestor(this);
        jf.add(ci);
        jf.pack();
    }//GEN-LAST:event_newSomethingActionPerformed

    private void informationTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationTblMouseClicked
        System.out.println(informationTbl.getSelectedColumn());
        System.out.println(informationTbl.getSelectedRow());
    }//GEN-LAST:event_informationTblMouseClicked

    private void addSome() {
        System.out.println("me ejecuto antes que el otro");
        JFrame jf = (JFrame) SwingUtilities.getWindowAncestor(this);
        Utils.deleteWindows(jf, ci);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable informationTbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newSomething;
    private javax.swing.JTextField searcher;
    // End of variables declaration//GEN-END:variables
}
