/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JMenu;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    InformationOfOption io;
    CreateInformation ci;
    InvoiceCreator ic;
    Map<String, String[]> columnIdentifiers = new HashMap<>();

    public Menu() {
        initComponents();
        gettingIdentifiersForTables();

        getContentPane().setBackground(new Color(19, 27, 40));

    }

    private void gettingIdentifiersForTables() {
        columnIdentifiers.put("Productos", new String[]{
            "ID|f",
            "Nombre|t",
            "Categoria|t",
            "Stock|t",
            "Precio|t",
            "Acciones|f",});

        columnIdentifiers.put("Categorias", new String[]{
            "ID|f",
            "Nombre Categoria|t",
            "Cantidad Productos|f",
            "Acciones|f",});

        columnIdentifiers.put("Proveedores", new String[]{
            "ID|f",
            "Nombre Proveedor|t",
            "Contacto|t",
            "Teléfono|t",
            "Email|t",
            "Acciones|f",});

        columnIdentifiers.put("Pedidos Web", new String[]{ // No se aprecia la tabla en las imágenes proporcionadas.
        // Completa estos títulos cuando tengas esa captura.
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        ProductsInformation = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenuBar1.setBackground(new java.awt.Color(19, 27, 40));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setOpaque(true);

        ProductsInformation.setBackground(new java.awt.Color(19, 27, 40));
        ProductsInformation.setText("Productos");
        ProductsInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getInformationTable(evt);
            }
        });
        jMenuBar1.add(ProductsInformation);

        jMenu3.setText("Categorias");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getInformationTable(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu1.setBackground(new java.awt.Color(19, 27, 40));
        jMenu1.setText("Proveedores");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getInformationTable(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Pedidos Web");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getInformationTable(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Crear Factura");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getInformationTable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getInformationTable

        Utils.deleteWindows(this, io);
        JMenu jm = (JMenu) evt.getSource();
        String key = jm.getText();
        io = new InformationOfOption(columnIdentifiers.get(key), key);
        getContentPane().add(io);
        pack();
    }//GEN-LAST:event_getInformationTable

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.out.println("estoy entrando aca en el metodo");
        Utils.deleteWindows(this, ic);
        ic = new InvoiceCreator();
        getContentPane().add(ic);
        pack();

    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ProductsInformation;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
