/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JMenu;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    InformationOfOption io;
    Map<String, String[]> columnIdentifiers = new HashMap<>();

    public Menu() {
        initComponents();
        gettingIdentifiersForTables();
    }

    private void gettingIdentifiersForTables() {
        columnIdentifiers.put("Productos", new String[]{
            "ID",
            "Nombre",
            "Categoria",
            "Stock",
            "Precio",
            "Acciones",
        });

        columnIdentifiers.put("Categorias", new String[]{
            "ID",
            "Nombre Categoria",
            "Cantidad Productos",
            "Acciones",
                
        });

        columnIdentifiers.put("Proveedores", new String[]{
            "ID",
            "Nombre Proveedor",
            "Contacto",
            "Teléfono",
            "Email",
            "Acciones",
                
        });

        columnIdentifiers.put("Pedidos Web", new String[]{ // No se aprecia la tabla en las imágenes proporcionadas.
        // Completa estos títulos cuando tengas esa captura.
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        ProductsInformation = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        ProductsInformation.setText("Productos");
        ProductsInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getInformationTable(evt);
            }
        });
        jMenuBar1.add(ProductsInformation);

        jMenu3.setText("Categorias");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getInformationTable(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu1.setText("Proveedores");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getInformationTable(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Pedidos Web");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getInformationTable(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Crear Factura");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getInformationTable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getInformationTable
        deleteWindows();
        JMenu jm = (JMenu) evt.getSource();
        String key = jm.getText();
        io = new InformationOfOption(columnIdentifiers.get(key), key.replaceAll(".$", ""));
        getContentPane().add(io);
        pack();
    }//GEN-LAST:event_getInformationTable

    private void deleteWindows() {
        try {
            getContentPane().remove(io);
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ProductsInformation;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
